(setq user-init-file (or load-file-name (buffer-file-name)))
(setq base (file-name-directory user-init-file))
(setq user-emacs-directory (file-name-directory user-init-file))

(add-to-list 'load-path (format "%srudel" base))
(add-to-list 'load-path (format "%srudel/obby" base))
(add-to-list 'load-path (format "%srudel/jupiter" base))
(add-to-list 'load-path (format "%srudel/socket" base))
(add-to-list 'load-path (format "%srudel/tls" base))

(require 'rudel)
(require 'rudel-obby-server)
(require 'rudel-interactive)
(require 'rudel-transport)
(require 'rudel-protocol)
(require 'rudel-backend)
(require 'rudel-obby)
(require 'rudel-socket)
(let ((info '(:address "0.0.0.0" :port 6522 :transport-backend (tcp . [object rudel-tcp-backend "tcp" (0 2) (listen connect)]) :protocol-backend (obby . [object rudel-obby-backend "obby" (0 3) (join host change-color track-subscriptions encrypt)]))))
  (rudel-host-session info))
