(setq user-init-file (or load-file-name (buffer-file-name)))
(setq base (file-name-directory user-init-file))
(setq user-emacs-directory base)

(add-to-list 'load-path (format "%srudel" base))
(add-to-list 'load-path (format "%srudel/obby" base))
(add-to-list 'load-path (format "%srudel/jupiter" base))
(add-to-list 'load-path (format "%srudel/socket" base))
(add-to-list 'load-path (format "%srudel/tls" base))

(require 'rudel)
(require 'rudel-obby-server)
(require 'rudel-interactive)
(require 'rudel-transport)
(require 'rudel-protocol)
(require 'rudel-backend)
(require 'rudel-obby)
(require 'rudel-socket)
